blank_issues_enabled: false
contact_links:
  - name: Request help
    url: https://github.com/cosee/ruler_scale_picker/discussions/categories/request-help
    about: Need assistance or guidance with the ruler_scale_picker package? We're here to help!
